### ISSUE TITLE
CNN for regression model performance

### ISSUE THREAD

**Issue by alexwu66666** [aqibsaeed/Estimation-of-Remaining-Useful-Life-using-CNN#2]
Hi there,

Based on the MSE value, do you think it is okay for us to use CNN to accomplish any regression tasks?

Best regards,
Chao

**Comment by aqibsaeed** [comment]
I suggest it is fine to use CNN, but do normalize both input and target. If you normalize the targets also denormalize them before computing any metric e.g., MSE etc.
